# Generated by Django 5.1.7 on 2025-03-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_savingsgoal_fixed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='percentage_value',
            field=models.IntegerField(blank=True, choices=[(5, '5%'), (10, '10%'), (15, '15%')], help_text="Debe elegir entre 5, 10 o 15% si selecciona 'Porcentaje'", null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='range_end',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Debe ingresar el fin del rango si selecciona 'Rango'", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='range_start',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Debe ingresar el inicio del rango si selecciona 'Rango'", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='rounding_to',
            field=models.IntegerField(blank=True, choices=[(5, 'Próximo 5'), (10, 'Próximo 10')], help_text="Debe elegir si se redondea al próximo 5 o 10 si selecciona 'Vuelto'", null=True),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Debe ingresar un monto fijo si selecciona 'Monto Fijo'", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='savings_mode',
            field=models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo'), ('rounding', 'Vuelto'), ('range', 'Rango')], default='percentage', max_length=20),
        ),
    ]
