# Generated by Django 5.1.7 on 2025-03-28 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_savingsgoal_percentage_value_savingsgoal_range_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('savings_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_savings', to='core.savingsgoal')),
            ],
        ),
    ]
